#!/usr/bin/env python3
# COMP3311 20T2 Final Exam
# Q7: tracklist for album, given by Albums.id
#     show performers/instruments for each track

import sys
import psycopg2

# ... put helper functions here ...

db = None
cur = None
usage = f"Usage: {sys.argv[0]} AlbumID"

# process command-line args

if len(sys.argv) < 2:
   print(usage)
   exit(1)
albumID = sys.argv[1]
if not albumID.isnumeric():
   print(usage)
   exit(1)

try:
   db = psycopg2.connect("dbname=music")
   cur = db.cursor()
   query = '''
   select * from findAlbum(%s)
   '''
   cur.execute(query,[albumID,])
   title, year, genre = cur.fetchone()
   if title is None:
      print('Invalid album ID')
      sys.exit()
   query = '''
   select * from album(%s)
   '''
   cur.execute(query, [albumID,])
   print(f"{title} ({year}) ({genre})")
   print("========================================")
   prevSong = ''
   for tup in cur.fetchall():
      album_id, album_title, song_id, song_trackNo, song_title, performer_id, performer_nam, instruments = tup
      if (prevSong != song_id):
         print(f"{song_trackNo:2d}. {song_title}")
      if instruments is None:
         print(f"{' ':8}The whole group")
      else:
         print(f"{' ':8}{performer_nam}: {instruments}")
      prevSong = song_id


except psycopg2.Error as err:
   print("DB error: ", err)
finally:
   if cur:
       cur.close()
   if db:
      db.close()

